### ISSUE TITLE
Create tooltips in the same place as RL's mouse tooltips

### ISSUE THREAD

**Issue by Enriath** [ryanxie0/lingering-click-tooltips#2]
The tooltips are placed with the bottom left corner on the cursor position, which looks very odd. At least an option to place it where the RL tooltips are (which iirc are pretty deterministic) would be lovely

**Comment by ryanxie0** [comment]
There's a tooltip offset setting for relative horizontal and vertical position under the location section in the config. I know it's not easy to use but it provides the most flexibility for the user (once you get the hang of using it).

If not fiddling with that, you seem to know that there is actually an option to convert them to behave the same way as the mouse tooltips. The tooltip offsets will not apply to any of those tooltips, keep that in mind.

**Comment by Enriath** [comment]
Oh I didn't actually realise that the offsets applied to all the tooltips; I thought it was only for the anchored ones. That's brilliant!
