### ISSUE TITLE
Tooltips are incorrectly restricted in fixed mode

### ISSUE THREAD

**Issue by Enriath** [ryanxie0/lingering-click-tooltips#4]
With 1.1, I noticed you added logic to keep the tooltips in the window itself. While this works perfectly fine in Resizeable mode, in Fixed mode it causes all the tooltips to be contained in the viewport, instead of being allowed on stuff like the inventory.

**Comment by ryanxie0** [comment]
Hmm, yeah it seems that the client viewport excludes the entire chatbox, minimap, and inventory areas in fixed mode, which makes sense. Obviously, I never tested the plugin in fixed mode myself (oops, oversight). Seems like the clamping code will need to refer to the app's window size and not the viewport dimensions from the RuneLite client API. I just need to figure out a way to get a handle on the window size in the code and it should be a simple fix.

**Comment by ryanxie0** [comment]
The update to v1.2 fixes the viewport restriction for Fixed mode users.
